### ISSUE TITLE
Explore what it would take to make it so land-uses repeat their harvest prescriptions

### ISSUE THREAD

**Issue by achmurzy** [LANDIS-II-Foundation/Extension-Land-Use-Change#10]
Check for data structure like Prescription.cs found in Biomass-Harvest. Check how harvest prescriptions are carried out on land-use change, and find a way to enable repeatable harvest prescriptions for a given land-use type across time-steps, rather than only on land-use type change.

**Comment by achmurzy** [comment]
Hi Luca, I pushed a new version of the code which may be the solution we need. In particular, in Main.cs where LANDIS checks if a LandUse for an ActiveSite is the same or different, in the block of code where the LandUse is the same for a given timestep, I added a call to the ApplyTo method at Line 129, which accesses the tree harvesting functionality in RemoveTree.cs. Harvesting should now occur across timesteps whether or not landuse type changes. Let me know if this is close to what you were thinking.

**Comment by llmorreale** [comment]
This sounds pretty close, but with the ability to make it optional.  We will have some more complexity that we will want to add to it later, but can you first implement it with a parameter in the text file to toggle it on/off for different land-usees? I'll test it and we can go from there.

**Comment by achmurzy** [comment]
Pushed code implementing the above. Try adding the following to a land-use definition in landuse.txt:

RepeatHarvest? Yes

**Comment by achmurzy** [comment]
Adjusted to accommodate multiple LandCoverChanges. Should be first parameter listed after LandCoverChange LandCoverChangeType
RepeatHarvest? Yes
Need to update documentation along with changes to LandCoverChange specification
