### ISSUE TITLE
Update documentation to reflect updates to LandCoverChanges

### ISSUE THREAD

**Issue by achmurzy** [LANDIS-II-Foundation/Extension-Land-Use-Change#14]
Provide description of InsectDefoliation functionality
Describe repeat harvest functionality for LandCoverChanges
Describe how to specify order of application of LandCoverChanges

**Comment by llmorreale** [comment]
Can we make this a priority? We have been trying to test the changes to the model but I can't figure out how to invoke these. I tried RepeatHarvest everywhere I could think of but the model didn't like it. From  looking at the code it looks like it is invoked from within the LandCover?

**Comment by achmurzy** [comment]
Yes I'll update this ASAP as I've made significant changes to the way the landuse.txt file is written and parsed to control modifications to land uses.

**Comment by achmurzy** [comment]
Closing for update to 1.3
