### ISSUE TITLE
The output log for LU+ shows incorrect values when you run both LU+ and Biomass Harvest

### ISSUE THREAD

**Issue by llmorreale** [LANDIS-II-Foundation/Extension-Land-Use-Change#15]
This only happens if you run the Biomass Harvest disturbance before LU+ in a timestep. I think it is because they are accessing the same site variable.

**Comment by achmurzy** [comment]
Hey Danelle I'm not so good at looking at LANDIS output, can you shed any light on this? To which output file was Luca referring?

**Comment by dlaflower** [comment]
When we implement LandCoverChange=Insect defoliation, the BiomassHarvest extension removes more biomass from the target species than it should be removing (in my case I had it set to remove 50% of the white pine and it removed 100%). In addition, BiomassHarvest removed all of the biomass for the species that should have been defoliated by insects (LU+ site output shows NO removal).

**Comment by dlaflower** [comment]
LU site-log.csv stopped being populated? (currently, output is completely empty csv files). This began after testing many iterations of LU+ with BiomassHarvest.  This happened on multiple computers.  On the second computer I noticed that it stopped working after running LU+ LandUseChange RemoveTrees with only one active species, which was set to 0% removal.  I have not been able to get the site-log.csv to show data again, even after changing parameter values.

**Comment by achmurzy** [comment]
This issue was a result of both LU+ and BiomassHarvest accessing static class members from the Biomass Library. It has been resolved by clearing the dictionary used for parsing percentages in the static CohortSelector class in Library Biomass Harvest. Stay away from static members kids
