### ISSUE TITLE
Explore how difficult it would be to have LU+ output maps of biomass removed instead of just a text file

### ISSUE THREAD

**Issue by llmorreale** [LANDIS-II-Foundation/Extension-Land-Use-Change#16]
Similar to most other extensions, it would be nice if we could optionally choose to have LU+ output maps (but this is not a high priority).

**Comment by achmurzy** [comment]
This functionality appears to exist in Extension Biomass Harvest, which now works properly in tandem with LU+. Closing pending more specific instructions
