### ISSUE TITLE
Prevent Establishment does not work

### ISSUE THREAD

**Issue by dlaflower** [LANDIS-II-Foundation/Extension-Land-Use-Change#19]
Error....
Found the name "PreventEstablishment" but expected one of these names:  Plant LandCoverChange LandUse
I tried it using LandCoverChange InsectDefoliation and RemoveTrees and it doesn't work with either.

**Comment by achmurzy** [comment]
Hi Danelle, this is working as intended. PreventEstablishment is specified before any LandCoverChanges. I'll make sure this is specificed in the new version of the documentation and try to give a more informative error message.
