### ISSUE TITLE
RepeatHarvest is inconsistent for RemoveTrees and InsectDefoliation

### ISSUE THREAD

**Issue by achmurzy** [LANDIS-II-Foundation/Extension-Land-Use-Change#20]
I thought that disabling RepeatHarvest for RemoveTrees was supposed to result in tree removal a single time for an ActiveSite for that particular LandUse. This seems like intended behavior. As for InsectDefoliation, RepeatHarvest is currently used to vary the rate of defoliation. However, it makes much more sense to make it so that RepeatHarvest toggles the actual defoliation process--I think Luca and I got mixed up on this point so I'll change it if this is what we need.

**Comment by dlaflower** [comment]
I agree that disabling RepeatHarvest for RemoveTrees should result in tree removal for a single timestep for an ActiveSite for that particular LandUse.  However, if RepeatHarvest=No, then no trees are removed at any timestep.  As for InsectDefoliation, I think it would be useful to toggle the actual defoliation process, allowing defoliation for a single timestep.  Currently how does RepeatHarvest vary the rate of defoliation?  I don't notice any differences.

**Comment by achmurzy** [comment]
Okay so the bug is that RemoveTrees won't even harvest once without RepeatHarvest. I'll look into that. We had intended to add an input to InsectDefoliation to specify a rate of change for defoliation but it isn't in there yet. We were going to use RepeatHarvest as the mechanism to vary the rate but in hindsight that's confusing and not what RepeatHarvest was intended to do, so I'll make the change to toggling defoliation as well.

**Comment by dlaflower** [comment]
Here is a bit more information regarding RemoveTrees and RepeatHarvest.  I
am conducting single cell simulations.  After reading the User Guide,
I set the input LandUse timestep 3 map to the match my LandCover type that
would RemoveTrees.  (for all other years the LandCover type matched
NoChange) (I also set RepeatHarvest=No).  This seems to work correctly.
Biomass was removed at the appropriate timestep and not again.  I still
think we want it to remove at timestep 1 even if RepeatHarvest is turned
off, but I cc.ed Luca on this in case he has some input.
[image: Inline image 1]
Thanks,
Danelle


On Mon, Sep 11, 2017 at 3:23 PM, Adam Chmurzynski <notifications@github.com>
wrote:

> Okay so the bug is that RemoveTrees won't even harvest once without
> RepeatHarvest. I'll look into that. We had intended to add an input to
> InsectDefoliation to specify a rate of change for defoliation but it isn't
> in there yet. We were going to use RepeatHarvest as the mechanism to vary
> the rate but in hindsight that's confusing and not what RepeatHarvest was
> intended to do, so I'll make the change to toggling defoliation as well.
>

##background for Luca (clipped from github issues):
I agree that disabling RepeatHarvest for RemoveTrees should result in tree
removal for a single timestep for an ActiveSite for that particular
LandUse. However, if RepeatHarvest=No, then no trees are removed at any
timestep. As for InsectDefoliation, I think it would be useful to toggle
the actual defoliation process, allowing defoliation for a single timestep.

**Comment by rmscheller** [comment]
Danielle and Alex,
We have been busy fixing a bug with Repeat Harvest.  These fixes are now complete.  You should consider upgrading to -v2 of all harvest libraries.  See: https://github.com/LANDIS-II-Foundation/Library-Harvest-Mgmt/commit/6463f1db142eb717698ff665a62a08a393f41842 and https://github.com/LANDIS-II-Foundation/Library-Harvest-Mgmt/issues/3

R

**Comment by achmurzy** [comment]
Hey Danelle, let's both update to v2 of these libraries and I'll close the issue once I've properly changed the RepeatHarvest functionality for InsectDefoliation.

**Comment by dlaflower** [comment]
Hi Adam,
I am not sure what you know about these things, but I am checking before I
do anything that I might regret.  I am running both BaseHarvest-3.1
<release candidate 1>, and BiomassHarvest-3.0.  I had the
Landis.Library.BiomassHarvest-v1.dll and
Landis.Library.Harvest.Management-v1.dll installed and everything worked.
When I removed the Landis.Library.Harvest.Management-v1.dll and replaced it
with Landis.Library.Harvest.Management-v2.dll, I got the following error:
[image: Inline image 1]
Do you know if I need a new installer or if I should uninstall and
reinstall the entire extensions (it seems like that it what the user guide
suggests).  If I need a new installer, where do I get it.  I did this for
LU+ once but it doesn't seem quite the same.

Thanks and I will be addressing the other emails shortly.
Danelle

**Comment by achmurzy** [comment]
We need a new installer for a new plug-in version. I can try to construct one but there's a good chance it'd be a nightmare--I'll just email rscheller asking for one.

**Comment by dlaflower** [comment]
great, thanks.

**Comment by achmurzy** [comment]
Looks like we're going to have to download the code and use the scripts Rob mentioned. I'll give it a shot and see if I can walk you through once I'm successful.

**Comment by dlaflower** [comment]
Great Adam,
I will just wait for you.
Thanks,
Danelle

**Comment by achmurzy** [comment]
Hi Danelle, I put the updated libraries up on slack and added the functionality for RepeatHarvest on InsectDefoliation so I'm closing the issue.
