### ISSUE TITLE
RemoveTrees should harvest at the beginning of the simulation

### ISSUE THREAD

**Issue by achmurzy** [LANDIS-II-Foundation/Extension-Land-Use-Change#21]
Make harvesting occur at the first time-step. Will investigate if this behavior is a result of some external library.

**Comment by achmurzy** [comment]
Harvesting at time-step 0 requires making sure a LandUse transition occurs with the initial maps, as you said--so we can close the issue as it isn't a bug per-se. This wasn't clear to me or you Danelle (something Luca must've learned the hard way as well). Maybe we should  make some note about this in the documentation?

**Comment by dlaflower** [comment]
Yes, clarifying it in the Land Use Maps section 1.1 would be useful, since where it is stated in 2.4.1 is under RepeatHarvests ("Normally changes to a site associated with LandCoverChanges are only applied when a site transitions to a LandUse associated with a set of LandCoverChanges from a different LandUse.").

**Comment by achmurzy** [comment]
I've modified the InsectDefoliation LandCoverChange so that after a single round of defoliation when RepeatHarvest is disabled, the delegate for CohortDefoliation(.Compute) is disabled, preventing succession modules from automatically defoliating in later timesteps. This is closer to the intended behavior of RepeatHarvest. I already updated LU+ to 1.3 (even though we aren't officially there yet) so you'll have to re-install the extension to get this change to work. Coincidentally this should be the same procedure as updating the Harvest v2 libraries, so we'll try to get it to work that way. Otherwise I can give you a (.exe) installer. I'll also update the documentation as we discussed then we can close this issue.

**Comment by achmurzy** [comment]
The new installer for LU+ (to version 1.3) I put on Slack should reflect these changes, including updated documentation.

**Comment by achmurzy** [comment]
Just to clarify, this has come up again multiple times -- LandCoverChanges are applied at the end of time-steps. So, for a simulation starting in 2010, with a timestep length of 5, the first application will be in 2014, the second in 2019, etc.

**Comment by achmurzy** [comment]
This is considered intended behavior right now.
