### ISSUE TITLE
Add keyword "All" to listing of species in a land-use so we don't have to write out all 100 species

### ISSUE THREAD

**Issue by achmurzy** [LANDIS-II-Foundation/Extension-Land-Use-Change#6]
Modify parsing of landuse.txt input file to automatically include all species for a land-use type if keyword "ALL" is specified

**Comment by achmurzy** [comment]
Cohort parameters, plant species lists, parsing are all done within extension 'SiteHarvest' -- check there for ALL parsing method or write it in a new version of SiteHarvest.

**Comment by llmorreale** [comment]
Does this mean we successfully modified it? Or that if we want to we must make changes to SiteHarvest?

**Comment by llmorreale** [comment]
Ok, it's not worth remaking SiteHarvest for this change.

**Comment by achmurzy** [comment]
You mentioned there used to be an "ALL" species parsing functionality -- we might be able to call it directly from some extension LandUse uses, probably SiteHarvest if it ever existed... or we need to change SiteHarvest. That extension seems to be in charge of everything from species lists to providing methods for parsing the land use file.

**Comment by achmurzy** [comment]
Looking at SiteHarvest there doesn't seem to be anything like it... it IS possible to specify ALL for harvesting cohorts, but not for including species at sites.

**Comment by achmurzy** [comment]
Closing for now
