### ISSUE TITLE
Add hook in LU+ to EnableEstablishment in new Succession, so that we can test it 

### ISSUE THREAD

**Issue by achmurzy** [LANDIS-II-Foundation/Extension-Land-Use-Change#7]
Add function call to new EnableEstablishment() method in Succession v1.2 for testing.

**Comment by achmurzy** [comment]
Added call to EnableEstablishment in Main.cs where model checks for change from currentLandUse to newLandUse.
It should be noted that EnableEstablishment will only occur when land-use type changes from one type to another. More code will need to be added to allow toggling establishment for a single land-use type at a single ActiveSite.

**Comment by achmurzy** [comment]
See Line 101 in Main.cs for the condition where EnableEstablishment() is called. Let me know if the hook should be added elsewhere, this is the place where the control flow originally threw an error for lacking functionality.

**Comment by llmorreale** [comment]
This works perfectly. Closing issue.
